  name: 'cicd-demo'
  on:
    push:
      branches:
        - master
  jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Start Build job
        run: |
          echo "Starting the build job."