  name: 'cicd-demo'
  on:
    push:
      branches:
        - master
  jobs:
    check-links:
      runs-on: ubuntu-latest
      steps:
        - name: Start Build job
          run: |
            echo "Starting the build job."
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup Java
          uses: actions/setup-java@v1
          with:
            java-version: 17
        - name: Check java version
          run: |
            java --version
        - name: Build demo project
          run: |
            ./gradlew build
